#!/usr/bin/env bash

packages=(
  .
  apps/app
  apps/ui
  apps/cms
  packages/types
  packages/schemas
  packages/strapi-plugin-google-map-picker
)

for i in "${packages[@]}"
do
  if test -f "$i/.tmuxinator.yml"; then
    echo "Loading $i/.tmuxinator.yml"
    $(cd "$i" && tmuxinator start)
  fi
done

tmux -L rems attach
